---@meta

---@class Font
---@field visible boolean
---@field font_family string
---@field font_height number
---@field color number
---@field position_x number
---@field position_y number
---@field background table
---@field apply fun(self: Font, settings: Font)
---@field destroy fun(self: Font)
