return {
    [ 1] = 'Mighty Strikes',
    [ 2] = 'Hundred Fists',
    [ 3] = 'Benediction',
    [ 4] = 'Manafont',
    [ 5] = 'Chainspell',
    [ 6] = 'Perfect Dodge',
    [ 7] = 'Invincible',
    [ 8] = 'Blood Weapon',
    [ 9] = 'Familiar',
    [10] = 'Soul Voice',
    [11] = 'Eagle Eye Shot',
    [12] = 'Meikyo Shisui',
    [13] = 'Mijin Gakure',
    [14] = 'Spirit Surge',
    [15] = 'Astral Flow',
    [16] = 'Azure Lore',
    [17] = 'Wild Card',
    [18] = 'Overdrive',
    [19] = 'Trance',
    [20] = 'Tabula Rasa',
    [21] = 'Bolster',
    [22] = 'Elemental Sforzo',
}
