local weaponskills_by_animation_id = {
  'Fast Blade',
  'Burning Blade',
  'Red Lotus Blade',
  'Shining Blade',
  'Seraph Blade',
  'Flat Blade',
  'Circle Blade',
  'Spirits Within',
  'Vorpal Blade',
  'Swift Blade',
  'Savage Blade',
  'Knights of Round',
  'Death Blossom',
  'Atonement',
  'Expiacion',
  'Combo',
  'Shoulder Tackle',
  'One Inch Punch',
  'Backhand Blow',
  'Raging Fists',
  'Spinning Attack',
  'Howling Fists',
  'Dragon Kick',
  'Asuran Fists',
  'Final Heaven',
  'Ascetic\'s Fury',
  'Stringing Pummel',
  'Tornado Kick',
  'Victory Smite',
  'Shijin Spiral',
  'Wasp Sting',
  'Viper Bite',
  'Shadowstitch',
  'Gust Slash',
  'Cyclone',
  'Energy Steal',
  'Energy Drain',
  'Dancing Edge',
  'Shark Bite',
  'Evisceration',
  'Mercy Stroke',
  'Mandalic Stab',
  'Mordant Rime',
  'Pyrrhic Kleos',
  'Aeolian Edge',
  'Raging Axe',
  'Smash Axe',
  'Gale Axe',
  'Avalanche Axe',
  'Spinning Axe',
  'Rampage',
  'Calamity',
  'Mistral Axe',
  'Decimation',
  'Onslaught',
  'Primal Rend',
  'Bora Axe',
  'Cloudsplitter',
  'Ruinator',
  '-',
  'Slice',
  'Dark Harvest',
  'Shadow of Death',
  'Nightmare Scythe',
  'Spinning Scythe',
  'Vorpal Scythe',
  'Guillotine',
  'Cross Reaper',
  'Spiral Hell',
  'Catastrophe',
  'Insurgency',
  'Infernal Scythe',
  'Quietus',
  'Entropy',
  '-',
  'Shining Strike',
  'Seraph Strike',
  'Brainshaker',
  'Starlight',
  'Moonlight',
  'Skullbreaker',
  'True Strike',
  'Judgement',
  'Hexa-Strike',
  'Black Halo',
  'Randgrith',
  'Mystic Boon',
  'Flash Nova',
  'Dagan',
  'Realmrazer',
  'Shield Break',
  'Iron Tempest',
  'Sturmwind',
  'Armor Break',
  'Keen Edge',
  'Weapon Break',
  'Raging Rush',
  'Full Break',
  'Steel Cyclone',
  'Metatron Torment',
  'King\'s Justice',
  'Fell Cleave',
  'Ukko\'s Fury',
  'Upheaval',
  '-',
  'Hard Slash',
  'Power Slash',
  'Frostbite',
  'Freezebite',
  'Shockwave',
  'Crescent Moon',
  'Sickle Moon',
  'Spinning Slash',
  'Ground Strike',
  'Herculean Slash',
  'Scourge',
  'Torcleaver',
  'Resolution',
  '-',
  '-',
  'Double Thrust',
  'Thunder Thrust',
  'Raiden Thrust',
  'Leg Sweep',
  'Penta-Thrust',
  'Vorpal Thrust',
  'Skewer',
  'Wheeling Thrust',
  'Impulse Drive',
  'Geirskogul',
  'Drakesbane',
  'Sonic Thrust',
  'Camlann\'s Torment',
  'Stardiver',
  '-',
  'Heavy Swing',
  'Rock Crusher',
  'Earth Crusher',
  'Starburst',
  'Sunburst',
  'Shell Crusher',
  'Full Swing',
  'Spirit Taker',
  'Retribution',
  'Gate of Tartarus',
  'Vidohunir',
  'Garland of Bliss',
  'Omniscience',
  'Tartarus Torpor',
  'Myrkr',
  'Blade: Rin',
  'Blade: Retsu',
  'Blade: Teki',
  'Blade: To',
  'Blade: Chi',
  'Blade: Ei',
  'Blade: Jin',
  'Blade: Ten',
  'Blade: Ku',
  'Blade: Metsu',
  'Blade: Kamu',
  'Blade: Yu',
  'Blade: Hi',
  'Blade: Shun',
  '-',
  'Tachi: Enpi',
  'Tachi: Hobaku',
  'Tachi: Goten',
  'Tachi: Kagero',
  'Tachi: Jinpu',
  'Tachi: Koki',
  'Tachi: Yukikaze',
  'Tachi: Gekko',
  'Tachi: Kasha',
  'Tachi: Kaiten',
  'Tachi: Rana',
  'Tachi: Ageha',
  'Tachi: Fudo',
  'Tachi: Shoha',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  'Flaming Arrow',
  'Piercing Arrow',
  'Dulling Arrow',
  '-',
  'Sidewinder',
  'Hot Shot',
  'Split Shot',
  'Sniper Shit',
  '-',
  'Slug Shot',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  'Blast Arrow',
  'Arching Arrow',
  'Empyreal Arrow',
  'Blast Shot',
  'Heavy Shot',
  'Detonator',
  'Namas Arrow',
  'Coronach',
  'Trueflight',
  'Leaden Salute',
  'Numbing Shot',
  'Sanguine Blade',
  'Cataclysm',
  'Refulgent Arrow',
  'Chant du Cygne',
  'Jishnu\'s Radiance',
  'Wildfire',
  'Rudra\'s Storm',
  'Requiescat',
  'Extenterator',
  'Shattersoul',
  'Apex Arrow',
  'Last Stand',
  'Glory Slash',
  'Uriel Blade',
}

return weaponskills_by_animation_id
