local weaponskills_by_animation_id = {
  { name = 'Fast Blade', attr = { 'Scission' } },
  { name = 'Burning Blade', attr = { 'Liquefaction' } },
  { name = 'Red Lotus Blade', attr = { 'Liquefaction', 'Detonation' } },
  { name = 'Shining Blade', attr = { 'Scission' } },
  { name = 'Seraph Blade', attr = { 'Scission' } },
  { name = 'Flat Blade', attr = { 'Impaction' } },
  { name = 'Circle Blade', attr = { 'Reverberation', 'Impaction' } },
  { name = 'Spirits Within', attr = {} },
  { name = 'Vorpal Blade', attr = { 'Scission', 'Impaction' } },
  { name = 'Swift Blade', attr = { 'Gravitation' } },
  { name = 'Savage Blade', attr = { 'Fragmentation', 'Scission' } },
  { name = 'Knights of Round', attr = { 'Light', 'Fusion' } },
  { name = 'Death Blossom', attr = { 'Fragmentation', 'Distortion' } },
  { name = 'Atonement', attr = { 'Fusion', 'Reverberation' } },
  { name = 'Expiacion', attr = { 'Distortion', 'Scission' } },
  { name = 'Combo', attr = { 'Impaction' } },
  { name = 'Shoulder Tackle', attr = { 'Reverberation', 'Impaction' } },
  { name = 'One Inch Punch', attr = { 'Compression' } },
  { name = 'Backhand Blow', attr = { 'Detonation' } },
  { name = 'Raging Fists', attr = { 'Impaction' } },
  { name = 'Spinning Attack', attr = { 'Liquefaction', 'Impaction' } },
  { name = 'Howling Fists', attr = { 'Transfixion', 'Impaction' } },
  { name = 'Dragon Kick', attr = { 'Fragmentation' } },
  { name = 'Asuran Fists', attr = { 'Gravitation', 'Liquefaction' } },
  { name = 'Final Heaven', attr = { 'Light', 'Fusion' } },
  { name = 'Ascetic\'s Fury', attr = { 'Fusion', 'Transfixion' } },
  { name = 'Stringing Pummel', attr = { 'Gravitation', 'Liquefaction' } },
  { name = 'Tornado Kick', attr = { 'Induration', 'Impaction', 'Detonation' } },
  { name = 'Victory Smite', attr = { 'Light', 'Fragmentation' } },
  { name = 'Shijin Spiral', attr = { 'Fusion', 'Reverberation' } },
  { name = 'Wasp Sting', attr = { 'Scission' } },
  { name = 'Viper Bite', attr = { 'Scission' } },
  { name = 'Shadowstitch', attr = { 'Reverberation' } },
  { name = 'Gust Slash', attr = { 'Detonation' } },
  { name = 'Cyclone', attr = { 'Detonation', 'Impaction' } },
  { name = 'Energy Steal', attr = {} },
  { name = 'Energy Drain', attr = {} },
  { name = 'Dancing Edge', attr = { 'Scission', 'Detonation' } },
  { name = 'Shark Bite', attr = { 'Fragmentation' } },
  { name = 'Evisceration', attr = { 'Gravitation', 'Transfixion' } },
  { name = 'Mercy Stroke', attr = { 'Darkness', 'Gravitation' } },
  { name = 'Mandalic Stab', attr = { 'Fusion', 'Compression' } },
  { name = 'Mordant Rime', attr = { 'Fragmentation', 'Distortion' } },
  { name = 'Pyrrhic Kleos', attr = { 'Distortion', 'Scission' } },
  { name = 'Aeolian Edge', attr = { 'Impaction', 'Scission', 'Detonation' } },
  { name = 'Raging Axe', attr = { 'Detonation', 'Impaction' } },
  { name = 'Smash Axe', attr = { 'Induration', 'Reverberation' } },
  { name = 'Gale Axe', attr = { 'Detonation' } },
  { name = 'Avalanche Axe', attr = { 'Scission', 'Impaction' } },
  { name = 'Spinning Axe', attr = { 'Liquefaction', 'Scission', 'Impaction' } },
  { name = 'Rampage', attr = { 'Scission' } },
  { name = 'Calamity', attr = { 'Scission', 'Impaction' } },
  { name = 'Mistral Axe', attr = { 'Fusion' } },
  { name = 'Decimation', attr = { 'Fusion', 'Reverberation' } },
  { name = 'Onslaught', attr = { 'Darkness', 'Gravitation' } },
  { name = 'Primal Rend', attr = { 'Gravitation', 'Reverberation' } },
  { name = 'Bora Axe', attr = { 'Scission', 'Detonation' } },
  { name = 'Cloudsplitter', attr = { 'Darkness', 'Fragmentation' } },
  { name = 'Ruinator', attr = { 'Distortion', 'Detonation' } },
  { name = '-', attr = { '???' } },
  { name = 'Slice', attr = { 'Scission' } },
  { name = 'Dark Harvest', attr = { 'Reverberation' } },
  { name = 'Shadow of Death', attr = { 'Induration', 'Reverberation' } },
  { name = 'Nightmare Scythe', attr = { 'Compression', 'Scission' } },
  { name = 'Spinning Scythe', attr = { 'Reverberation', 'Scission' } },
  { name = 'Vorpal Scythe', attr = { 'Transfixion', 'Scission' } },
  { name = 'Guillotine', attr = { 'Induration' } },
  { name = 'Cross Reaper', attr = { 'Distortion' } },
  { name = 'Spiral Hell', attr = { 'Distortion', 'Scission' } },
  { name = 'Catastrophe', attr = { 'Darkness', 'Gravitation' } },
  { name = 'Insurgency', attr = { 'Fusion', 'Compression' } },
  { name = 'Infernal Scythe', attr = { 'Compression', 'Reverberation' } },
  { name = 'Quietus', attr = { 'Darkness', 'Distortion' } },
  { name = 'Entropy', attr = { 'Gravitation', 'Reverberation' } },
  { name = '-', attr = { '???' } },
  { name = 'Shining Strike', attr = { 'Impaction' } },
  { name = 'Seraph Strike', attr = { 'Impaction' } },
  { name = 'Brainshaker', attr = { 'Reverberation' } },
  { name = 'Starlight', attr = {} },
  { name = 'Moonlight', attr = {} },
  { name = 'Skullbreaker', attr = { 'Induration', 'Reverberation' } },
  { name = 'True Strike', attr = { 'Detonation', 'Impaction' } },
  { name = 'Judgement', attr = { 'Impaction' } },
  { name = 'Hexa Strike', attr = { 'Fusion' } },
  { name = 'Black Halo', attr = { 'Fragmentation', 'Compression' } },
  { name = 'Randgrith', attr = { 'Light', 'Fragmentation' } },
  { name = 'Mystic Boon', attr = {} },
  { name = 'Flash Nova', attr = { 'Induration', 'Reverberation' } },
  { name = 'Dagan', attr = {} },
  { name = 'Realmrazer', attr = { 'Fusion', 'Impaction' } },
  { name = 'Shield Break', attr = { 'Impaction' } },
  { name = 'Iron Tempest', attr = { 'Scission' } },
  { name = 'Sturmwind', attr = { 'Reverberation', 'Scission' } },
  { name = 'Armor Break', attr = { 'Impaction' } },
  { name = 'Keen Edge', attr = { 'Compression' } },
  { name = 'Weapon Break', attr = { 'Impaction' } },
  { name = 'Raging Rush', attr = { 'Induration', 'Reverberation' } },
  { name = 'Full Break', attr = { 'Distortion' } },
  { name = 'Steel Cyclone', attr = { 'Distortion', 'Detonation' } },
  { name = 'Metatron Torment', attr = { 'Light', 'Fusion' } },
  { name = 'King\'s Justice', attr = { 'Fragmentation', 'Scission' } },
  { name = 'Fell Cleave', attr = { 'Impaction', 'Detonation', 'Scission' } },
  { name = 'Ukko\'s Fury', attr = { 'Light', 'Fragmentation' } },
  { name = 'Upheaval', attr = { 'Fusion', 'Compression' } },
  { name = '-', attr = { '???' } },
  { name = 'Hard Slash', attr = { 'Scission' } },
  { name = 'Power Slash', attr = { 'Transfixion' } },
  { name = 'Frostbite', attr = { 'Induration' } },
  { name = 'Freezebite', attr = { 'Induration', 'Detonation' } },
  { name = 'Shockwave', attr = { 'Reverberation' } },
  { name = 'Crescent Moon', attr = { 'Scission' } },
  { name = 'Sickle Moon', attr = { 'Scission', 'Impaction' } },
  { name = 'Spinning Slash', attr = { 'Fragmentation' } },
  { name = 'Ground Strike', attr = { 'Fragmentation', 'Distortion' } },
  { name = 'Herculean Slash', attr = { 'Induration', 'Impaction', 'Detonation' } },
  { name = 'Scourge', attr = { 'Light', 'Fusion' } },
  { name = 'Torcleaver', attr = { 'Light', 'Distortion' } },
  { name = 'Resolution', attr = { 'Fragmentation', 'Scission' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = 'Double Thrust', attr = { 'Transfixion' } },
  { name = 'Thunder Thrust', attr = { 'Transfixion', 'Impaction' } },
  { name = 'Raiden Thrust', attr = { 'Transfixion', 'Impaction' } },
  { name = 'Leg Sweep', attr = { 'Impaction' } },
  { name = 'Penta-Thrust', attr = { 'Compression' } },
  { name = 'Vorpal Thrust', attr = { 'Reverberation', 'Transfixion' } },
  { name = 'Skewer', attr = { 'Transfixion', 'Impaction' } },
  { name = 'Wheeling Thrust', attr = { 'Fusion' } },
  { name = 'Impulse Drive', attr = { 'Gravitation', 'Induration' } },
  { name = 'Geirskogul', attr = { 'Light', 'Distortion' } },
  { name = 'Drakesbane', attr = { 'Fusion', 'Transfixion' } },
  { name = 'Sonic Thrust', attr = { 'Transfixion', 'Scission' } },
  { name = 'Camlann\'s Torment', attr = { 'Light', 'Fragmentation' } },
  { name = 'Stardiver', attr = { 'Gravitation', 'Transfixion' } },
  { name = '-', attr = { '???' } },
  { name = 'Heavy Swing', attr = { 'Impaction' } },
  { name = 'Rock Crusher', attr = { 'Impaction' } },
  { name = 'Earth Crusher', attr = { 'Detonation', 'Impaction' } },
  { name = 'Starburst', attr = { 'Compression', 'Reverberation' } },
  { name = 'Sunburst', attr = { 'Compression', 'Reverberation' } },
  { name = 'Shell Crusher', attr = { 'Detonation' } },
  { name = 'Full Swing', attr = { 'Liquefaction', 'Impaction' } },
  { name = 'Spirit Taker', attr = {} },
  { name = 'Retribution', attr = { 'Gravitation', 'Reverberation' } },
  { name = 'Gate of Tartarus', attr = { 'Darkness', 'Distortion' } },
  { name = 'Vidohunir', attr = { 'Fragmentation', 'Distortion' } },
  { name = 'Garland of Bliss', attr = { 'Fusion', 'Reverberation' } },
  { name = 'Omniscience', attr = { 'Gravitation', 'Transfixion' } },
  { name = 'Tartarus Torpor', attr = {} },
  { name = 'Myrkr', attr = {} },
  { name = 'Blade: Rin', attr = { 'Transfixion' } },
  { name = 'Blade: Retsu', attr = { 'Scission' } },
  { name = 'Blade: Teki', attr = { 'Reverberation' } },
  { name = 'Blade: To', attr = { 'Induration', 'Detonation' } },
  { name = 'Blade: Chi', attr = { 'Transfixion', 'Impaction' } },
  { name = 'Blade: Ei', attr = { 'Compression' } },
  { name = 'Blade: Jin', attr = { 'Detonation', 'Impaction' } },
  { name = 'Blade: Ten', attr = { 'Gravitation' } },
  { name = 'Blade: Ku', attr = { 'Gravitation', 'Transfixion' } },
  { name = 'Blade: Metsu', attr = { 'Darkness', 'Fragmentation' } },
  { name = 'Blade: Kamu', attr = { 'Fragmentation', 'Compression' } },
  { name = 'Blade: Yu', attr = { 'Reverberation', 'Scission' } },
  { name = 'Blade: Hi', attr = { 'Darkness', 'Gravitation' } },
  { name = 'Blade: Shun', attr = { 'Fusion', 'Impaction' } },
  { name = '-', attr = { '???' } },
  { name = 'Tachi: Enpi', attr = { 'Transfixion', 'Scission' } },
  { name = 'Tachi: Hobaku', attr = { 'Induration' } },
  { name = 'Tachi: Goten', attr = { 'Transfixion', 'Impaction' } },
  { name = 'Tachi: Kagero', attr = { 'Liquefaction' } },
  { name = 'Tachi: Jinpu', attr = { 'Scission', 'Detonation' } },
  { name = 'Tachi: Koki', attr = { 'Reverberation', 'Impaction' } },
  { name = 'Tachi: Yukikaze', attr = { 'Induration', 'Detonation' } },
  { name = 'Tachi: Gekko', attr = { 'Distortion', 'Reverberation' } },
  { name = 'Tachi: Kasha', attr = { 'Fusion', 'Compression' } },
  { name = 'Tachi: Kaiten', attr = { 'Light', 'Fragmentation' } },
  { name = 'Tachi: Rana', attr = { 'Gravitation', 'Induration' } },
  { name = 'Tachi: Ageha', attr = { 'Compression', 'Scission' } },
  { name = 'Tachi: Fudo', attr = { 'Light', 'Distortion' } },
  { name = 'Tachi: Shoha', attr = { 'Fragmentation', 'Compression' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = 'Flaming Arrow', attr = { 'Liquefaction', 'Transfixion' } },
  { name = 'Piercing Arrow', attr = { 'Reverberation', 'Transfixion' } },
  { name = 'Dulling Arrow', attr = { 'Liquefaction', 'Transfixion' } },
  { name = '-', attr = { '???' } },
  { name = 'Sidewinder', attr = { 'Reverberation', 'Transfixion', 'Detonation' } },
  { name = 'Hot Shot', attr = { 'Liquefaction', 'Transfixion' } },
  { name = 'Split Shot', attr = { 'Reverberation', 'Transfixion' } },
  { name = 'Sniper Shot', attr = { 'Liquefaction', 'Transfixion' } },
  { name = '-', attr = { '???' } },
  { name = 'Slug Shot', attr = { 'Reverberation', 'Transfixion', 'Detonation' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = '-', attr = { '???' } },
  { name = 'Blast Arrow', attr = { 'Induration', 'Transfixion' } },
  { name = 'Arching Arrow', attr = { 'Fusion' } },
  { name = 'Empyreal Arrow', attr = { 'Fusion', 'Transfixion' } },
  { name = 'Blast Shot', attr = { 'Induration', 'Transfixion' } },
  { name = 'Heavy Shot', attr = { 'Fusion' } },
  { name = 'Detonator', attr = { 'Fusion', 'Transfixion' } },
  { name = 'Namas Arrow', attr = { 'Light', 'Distortion' } },
  { name = 'Coronach', attr = { 'Darkness', 'Fragmentation' } },
  { name = 'Trueflight', attr = { 'Fragmentation', 'Scission' } },
  { name = 'Leaden Salute', attr = { 'Gravitation', 'Transfixion' } },
  { name = 'Numbing Shot', attr = { 'Impaction', 'Detonation' } },
  { name = 'Sanguine Blade', attr = {} },
  { name = 'Cataclysm', attr = { 'Compression', 'Reverberation' } },
  { name = 'Refulgent Arrow', attr = { 'Reverberation', 'Transfixion' } },
  { name = 'Chant du Cygne', attr = { 'Light', 'Distortion' } },
  { name = 'Jishnu\'s Radiance', attr = { 'Light', 'Fusion' } },
  { name = 'Wildfire', attr = { 'Darkness', 'Gravitation' } },
  { name = 'Rudra\'s Storm', attr = { 'Darkness', 'Distortion' } },
  { name = 'Requiescat', attr = { 'Gravitation', 'Scission' } },
  { name = 'Extenterator', attr = { 'Fragmentation', 'Scission' } },
  { name = 'Shattersoul', attr = { 'Gravitation', 'Induration' } },
  { name = 'Apex Arrow', attr = { 'Fragmentation', 'Transfixion' } },
  { name = 'Last Stand', attr = { 'Fusion', 'Reverberation' } },
  { name = 'Glory Slash', attr = { 'Light', 'Fusion' } },
  { name = 'Uriel Blade', attr = { 'Light', 'Fragmentation' } },
}

return weaponskills_by_animation_id
